version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.development
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp
    network_mode: "host"
