default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<: *default
  database: python_toolbox_development

test:
  <<: *default
  database: python_toolbox_test

production:
  <<: *default
  database: python_toolbox_production
  username: ubuntu
  password: password
