default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: python_toolbox_development

test:
  <<: *default
  database: python_toolbox_test

production:
  <<: *default
  database: python_toolbox_production
  username: ubuntu
  password: password
